### ISSUE TITLE
JSON Schema definitions of 'int64' and 'uint64' types have ranges not representable in 64 bits

### ISSUE THREAD

**Issue by johnbartholomew** [opencontainers/runtime-spec#1051]
In schema/defs.json, there are definitions for 'int64' and 'uint64' types:

```
        "int64": {
            "type": "integer",
            "minimum": -9223372036854776000,
            "maximum": 9223372036854776000
        },
        "uint64": {
            "type": "integer",
            "minimum": 0,
            "maximum": 18446744073709552000
        },
```

These minimum and maximum values are not representable in a normal signed/unsigned 64-bit integer. Is there a reason that these definitions don't match normal INT64_MIN/INT64_MAX/UINT64_MAX values? The other sized integer type definitions in the schema have the min/max values I would expect.

**Comment by thaJeztah** [comment]
I see it was added in https://github.com/opencontainers/runtime-spec/pull/313, and see no mention of a specific reason, so this _may_ be an oversight, but pinging @vbatts @mrunalp in case there's some odd reason I'm overlooking.

**Comment by thaJeztah** [comment]
Discussed with some people, and this was likely an oversight; @johnbartholomew are you interested in contributing a pull request to fix?
