### ISSUE TITLE
[proposal/rfc] Use github-native review process, say goodbye to pullapprove

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runtime-spec#1057]
(similar to https://github.com/opencontainers/runc/issues/2388)

Pullappove was probably added when github did not have its own mechanism to do LGTMs. For quite some time, such a mechanism exists: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/approving-a-pull-request-with-required-reviews

There is also a mechanism to require a certain number of LGTMs before it is possible to merge a PR: https://help.github.com/en/github/administering-a-repository/about-required-reviews-for-pull-requests, although I don't think it is necessary, since all the moderators here are able to count how many green check marks are there in the top left corner of a PR page.

So, unless I am missing something, there is no value that pullapprove adds to what github has.

Please let me know what you think, @opencontainers/runtime-spec-maintainers

**Comment by vbatts** [comment]
yes, please

**Comment by crosbymichael** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM (non binding)

**Comment by kolyshkin** [comment]
@tianon @mrunalp @caniszczyk PTAL

**Comment by tianon** [comment]
LGTM, although I think it's useful to have it require the proper number (requires less cognitive effort to verify, so more likely to get it right consistently)

**Comment by mrunalp** [comment]
LGTM

**Comment by thaJeztah** [comment]
> although I think it's useful to have it require the proper number

Yes, it's possible to configure the number of approvals required (and to disallow "stale" reviews)

**Comment by crosbymichael** [comment]
LGTM

**Comment by kolyshkin** [comment]
Looks like we have a consensus, and so we can move on to implementing the change. I do not have any admin rights over that repo, so can anyone from @opencontainers/runtime-spec-maintainers please implement that?

**Comment by cyphar** [comment]
@caniszczyk can set this up.

**Comment by kolyshkin** [comment]
Alas, this is still not implemented, nor do I have admin access to do it. @caniszczyk please? 🙏🏻

**Comment by AkihiroSuda** [comment]
Seems completed
