### ISSUE TITLE
charter link in README.md is broken

### ISSUE THREAD

**Issue by jmgurney** [opencontainers/runtime-spec#1089]
The current README.md has a link in the Table of Contents to charter, but when clicking on it, it returns a 404 - page not found on the opencontainers.org website.

**Comment by cyphar** [comment]
Yeah it needs to point to https://github.com/opencontainers/tob/blob/master/CHARTER.md. The URL changed last year.

**Comment by jmgurney** [comment]
This appears to have been fixed.  Not sure when.
