### ISSUE TITLE
Rust support for spec

### ISSUE THREAD

**Issue by utam0k** [opencontainers/runtime-spec#1106]
This project currently only provides the specification as a library in Go.
Is there any reason for this?
I think Rust is one of the languages that can contribute to this community. That's why I'd like to support Rust in this repository and help it out.
I'm working on a container runtime in Rust. There, of course, there is a library for parsing specs. How about bringing this to this repository?
https://github.com/utam0k/youki/blob/e52f304b0df6a26824ab13112999c9b2ad353e71/src/spec.rs

**Comment by tianon** [comment]
I think the Go code here is intended as a reference implementation -- I can't speak for all the maintainers, but I don't think we really want to be maintaining multiple concurrent implementations of the spec format parsing directly. :sweat_smile:
