### ISSUE TITLE
Travis CI not working?

### ISSUE THREAD

**Issue by rata** [opencontainers/runtime-spec#1121]
Travis seems to not be working anymore. Currently open PRs, like this: https://github.com/opencontainers/runtime-spec/pull/1120, have only the DCO check. And merged PRs, that I _think_  did run tests with travis at the time, do not show the test run either: https://github.com/opencontainers/runtime-spec/pull/1074/checks

I also see on other github repos that travis _was_ running, that is not running anymore and that merged PRs that did run travis CI, don't show the output anymore either (as it seems to happen here).

Also, the travis-ci.org website says that "Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on". I haven't checked if it is related, but it smells as it might be :)

Maybe we should migrate to travis-ci.com or some other CI?

**Comment by tianon** [comment]
Oh hmm, good catch -- I guess we migrated other repos, but missed this one.  IMO a contribution moving to GitHub Actions would be pretty well appreciated (I don't think we do anything very complex here that warrants using a different solution like the Fedora tests in runc, for example).

Also worth noting that #1078 is related, at least tangentially.

**Comment by h-vetinari** [comment]
This can probably be closed as of https://github.com/opencontainers/runtime-spec/commit/a3c33d663ebc56c4d35dbceaa447c7bf37f6fab3 / #1128

**Comment by tianon** [comment]
Nice catch, thanks!
