### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/runtime-spec#1127]
This is listed under "Tier 1: Replace Immediately" in the Inclusive Naming Initiative:
https://inclusivenaming.org/word-lists/tier-1/#master

**Comment by jdolitsky** [comment]
Just realized a mistake with #1128 .. referencing `main`, so no builds triggering. Do we want to address this issue, or modify the github actions to reference `master`? Apologies for not catching this

cc @tianon @cyphar @vbatts @caniszczyk

**Comment by caniszczyk** [comment]
I did the rename, github makes this trivial now and even updates the existing PRs
