### ISSUE TITLE
PRs are not mergeable due to the pending `code-review/pullapprove`

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runtime-spec#1174]
PRs are not mergeable due to the pending `code-review/pullapprove`

![image](https://user-images.githubusercontent.com/9248427/211940108-d79457ec-1d26-4291-bd0c-70ff8a730c46.png)
https://github.com/opencontainers/runtime-spec/pull/1169#issuecomment-1371534320

This should be removable in https://github.com/opencontainers/runtime-spec/settings (`Branches` → `Branch protection rules`), but it looks like I don't have an access to https://github.com/opencontainers/runtime-spec/settings (although I have an access to https://github.com/opencontainers/runc/settings .)

**Comment by AkihiroSuda** [comment]
@caniszczyk @amye PTAL 🙏

**Comment by amye** [comment]
Try it now, we probably need to change these settings.

**Comment by AkihiroSuda** [comment]
Thank you!

Looks like the merge button is now clickable but the pullaprove check still appears in the "Some checks haven’t completed yet" section. Can we just completely disable it?
