### ISSUE TITLE
Proposal: Support filter (Includes and Excludes) feature in LinuxSyscall

### ISSUE THREAD

**Issue by y1r** [opencontainers/runtime-spec#1238]
Currently, [moby/moby supports filter (Includes and Excludes) notation in Syscall definition.](https://github.com/moby/moby/blob/7bc56c53657dbf405db89e55d4b120f695848058/profiles/seccomp/seccomp.go#L59-L66) By doing so, we can enable or disable some syscalls by checking Capabilities, Architectures, and MinKernel. However, this feature is not supported in OCI runtime spec, so currently it is partially handled by high-level container runtime (i.e. https://github.com/containerd/containerd/blob/643fa70a7d7716e1e8138a3f2b2ce0532886676c/contrib/seccomp/seccomp_default.go#L500-L741) . I think it should be handled by low-level container runtime because:
- Enabling/disabling syscalls depends on current capabilities is very basic and important feature
- Kubernetes supports LocalhostProfile feature that reads local seccomp definition but the json seccomp type seems ambiguous (there're two standards, one is in moby/moby, and the other is in oci-runtime-spec) . I thought that it can understand moby/moby notation at first, but actually it only understand oci runtime spec json.

My current goal is implementing filter (Includes and Excludes) with capabilities. Filtering by architectures and MinKernel is currently out-of-scope. Anyone interests this feature, it will be okay to be included.

**Comment by utam0k** [comment]
@AkihiroSuda @giuseppe I think this feature is good in itself, but I wonder if we should put it into high-level runtime or kubelet. What do you think?

@saschagrunert I'd like to hear input from CRI-O.

**Comment by AkihiroSuda** [comment]
I think this should be in CRI API

**Comment by cyphar** [comment]
I don't think this belongs in runtime-spec -- seccomp cannot see the set of capabilities so this logic doesn't belong in the seccomp configuration of the runtime-spec.

**Comment by saschagrunert** [comment]
> … it is partially handled by high-level container runtime …

I don't see an issue with that, it seems to be the right place to handle capabilities together with seccomp rules.

**Comment by giuseppe** [comment]
I also think that this feature doesn't belong to the OCI runtime and it fits better in the CRI runtime

**Comment by utam0k** [comment]
@AkihiroSuda @cyphar @saschagrunert @giuseppe Thank you for providing your input. 🙏

**Comment by utam0k** [comment]
@y1r Let's create this feature and discuss it in CRI API! May I ask you to create it?
https://github.com/kubernetes/kubernetes
