### ISSUE TITLE
Build error with clang++ 17

### ISSUE THREAD

**Issue by Ecordonnier** [opencontainers/runtime-spec#1243]
Hello,
those [lines](https://github.com/opencontainers/runtime-spec/blob/68346ed538d50d73869d48edb009fb0c2d1dd66e/schema/config-schema.json#L150) in schema/config-schema.json are problematic in C++:

```
                    "required": [
                        "class"
                    ],
                    "properties": {
                        "class": {
```                        

  
 
 "class" is a reserved c++ keyword, and thus the generated header-file triggers an error when trying to compile with clang++ 17:
 ```
 /usr/include/ocispec/runtime_spec_schema_config_schema.h:140:11: error: expected member name or ';' after declaration specifiers
|   140 |     char *class;
|       |     ~~~~  ^
| 1 error generated.
```
 
 As far as I understand, since the generated header-file contains "#ifdef __cplusplus", it is supposed to be parseable by a c++ compiler.

**Comment by utam0k** [comment]
@Ecordonnier Is there anything we can do?

**Comment by Ecordonnier** [comment]
Just renaming class to ioprioclass is enough.  I'll send a patch once I've gone through the upstreaming review process at my company.

**Comment by Ecordonnier** [comment]
Unfortunately I'm not aware of another way to make this file compile with clang++ (other than patching clang). Currently it is not a valid c++ file.

**Comment by utam0k** [comment]
How about writing the parser by hand instead of auto-generating it?.

**Comment by utam0k** [comment]
In fact, both Rust and Go do.

**Comment by utam0k** [comment]
Needs more reason.
