### ISSUE TITLE
> The doc viewer is now implemented in the goplsv/0.16 pre-release; please try it out.

### ISSUE THREAD

**Issue by Sec32fun32** [opencontainers/runtime-spec#1267]
> The doc viewer is now implemented in the goplsv/0.16 pre-release; please try it out.

:+1: LGTM. This is perfect for the purpose of working on documentation for my packages. Changes I make to doc comments are immediately reflected in the rendered page (once I refresh) which is nice.

As far as I can recall I've never used source actions before, which is probably why I couldn't find it at first (or at least that's what I'm telling myself). It may be worth documenting that with screenshots. I also had no clue the "Browse assembly for function" feature existed.

> I wonder whether there is a way for the VS Code Go extension to inject a little bit of policy into the showDocument handler to make certain URLs open an internal browser frame. Worth investigating; it might be a small change overall.

I'm threw together a patch that uses the language client's middleware config to intercept the showDocument request and opens a webview within vscode instead. The UX isn't wonderful but it works.

With respect to my other desire - integrating the documentation viewer into vscode - @adonovan @hyangah what would you think of adding a hook that allows a 3rd party extension to override the webview renderer? It would be a bit tricky to design well, but I could add a method to the extension API in `extension/src/extensionAPI.ts` that registered a handler, then check for and call that handler in `openGoplsInWebview`. That would allow me to experiment with a custom documentation viewer in a separate extension. The HTML coming from gopls is very clean. It shouldn't be too hard to apply styling to make it fit with the user's theme, and I could remove the navigation dropdown and create a side panel to replace it.

<details><summary>showDocument middlware</summary>

```typescript
// Use this as middleware.window in the call to new GoLanguageClient in extension/src/language/goLanguageServer.ts
const windowMiddleware = {
	async showDocument(params, next) {
		// TODO: The typing for next is a lie - it doesn't actually expect us to
		// pass a cancellation token. Also, it doesn't pass the token to us so
		// there's not much we can do. The latest (unreleased) version of
		// vscode-languageclient *does* pass us the token, so once that's
		// released and we've updated, we can remove this hack.
		const showDocument = next as (params: ShowDocumentParams) => Promise<ShowDocumentResult>;

		try {
			if (/^http:\/\/127\.0\.0\.1:\d+\/gopls/.test(params.uri)) {
				await openGoplsInWebview(params);
				return { success: true };
			}
		} catch (_) {
			// If this fails, try opening the normal way
		}

		return showDocument(params);
	}
}

async function openGoplsInWebview(params: ShowDocumentParams) {
	const externalUri = await vscode.env.asExternalUri(vscode.Uri.parse(params.uri));

	const panel = vscode.window.createWebviewPanel('gopls', 'gopls', vscode.ViewColumn.Active);
	panel.webview.options = { enableScripts: true };
	panel.webview.html = `<html>
		<head>
			<style>
				body {
					padding: 0;
					background: white;
					overflow: hidden;
				}

				iframe {
					border: 0;
					width: 100%;
					height: 100vh;
				}
			</style>
		</head>
		<body>
			<iframe src="${externalUri.toString(true)}"></iframe>
		</body>
	</html>`;
}
```

</details>

_Originally posted by @firelizzard18 in https://github.com/golang/go/issues/55861#issuecomment-2183219760_

**Comment by tianon** [comment]
This looks like it was accidental (although how you "accidentally" cross-posted a comment from golang/go here is a little beyond my ability to understand).

**Comment by cyphar** [comment]
I think it's spam.

**Comment by thaJeztah** [comment]
Yeah; spam account; created a month ago; forked a bunch of repos and started to review already merged PRs and opening random tickets.
