### ISSUE TITLE
[Tracker] common distributable archive format

### ISSUE THREAD

**Issue by vbatts** [opencontainers/runtime-spec#302]
Per the ROADMAP.md

**Comment by vbatts** [comment]
Related #293

**Comment by vbatts** [comment]
related #11

**Comment by wking** [comment]
Previous list discussion in [1,2].  There are more threads talking
about hashing/verification, and whether that falls under
“distribution” depends on how tightly you want to scope this tracker.
Let me know if you want links to list threads discussing
hashing/verification.

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/uo11avcWlQQ
     Subject: appc + oci harmonization progress
     Date: Thu, 13 Aug 2015 03:55:58 +0000
     Message-ID: <CAD2oYtPPg02Tr2giHzxgX_weVCP3FCDTx+EZ2o_TMwaj6MDwRw@mail.gmail.com>
[2]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/OqnUp4jOacs
     Subject: distributable and decentralized values
     Date: Fri, 28 Aug 2015 16:35:56 -0400
     Message-ID: <CAN6Zp5x++Xd_2X1EztU9KOD_3pdURMBdOvRdq4uqP8kN2w+rgA@mail.gmail.com>

**Comment by mrunalp** [comment]
This belongs to the image-spec.
