### ISSUE TITLE
[Tracker] Base Config Compatibility 

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/runtime-spec#303]
(copied from roadmap.md)
Ensure that the base configuration format is viable for various platforms
Systems:
- Solaris
- Windows
- Linux

**Comment by vbatts** [comment]
We'll need some folks to contribute the technical requirements for these platforms, as Linux is what is currently getting our attention.

**Comment by RobDolinMS** [comment]
Currently comparing the Spec structs from:
* https://github.com/docker/containerd/blob/master/vendor/src/github.com/opencontainers/specs/specs-go/config.go
* https://github.com/docker/docker/blob/master/libcontainerd/windowsoci/oci_windows.go

**Comment by RobDolinMS** [comment]
Have been in-touch with Jesse from Oracle and expecting more info soon.

**Comment by hqhq** [comment]
Looks like this needs to be addressed before 1.0, I'm adding it to 1.0 milestone.

**Comment by jlbutler** [comment]
@RobDolinMS as you're heading this effort up, can you make a call on whether or not the final round of cleanup in PR #673 is enough to close the issue out? If not, please let me know what else I can do to wrap this up.

**Comment by crosbymichael** [comment]
Since #673 was merged I'm going to close this as resolved.  If this is not the case please open actionable issues that can be addressed.
