### ISSUE TITLE
[Tracker] Live Container Updates

### ISSUE THREAD

**Issue by vbatts** [opencontainers/runtime-spec#305]
https://github.com/opencontainers/specs/blob/master/ROADMAP.md#live-container-updates

This needs to be an optional feature.
 and per the life-cycle discussions, this is left to the operator where hooks that would happen after the "start" action of the container.

**Comment by hqhq** [comment]
Related discussion: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/mWZVREVL9T8

**Comment by wking** [comment]
Cross referencing earlier discussion in #17.
