### ISSUE TITLE
Rename project to runtime-spec

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/runtime-spec#357]
It's been suggested to rename this repo by the TOB to improve clarity:
https://groups.google.com/a/opencontainers.org/forum/#!topic/tob/P6HbXcwpE3k

**Comment by caniszczyk** [comment]
cc: @opencontainers/tob

**Comment by wking** [comment]
On Fri, Mar 25, 2016 at 10:40:04AM -0700, Chris Aniszczyk wrote:
> It's been suggested to rename this repo by the TOB to improve clarity:
> https://groups.google.com/a/opencontainers.org/forum/#!topic/tob/P6HbXcwpE3k

opencontainers/runtime-spec works for me.

**Comment by philips** [comment]
opencontainers/runtime-spec works for me too

**Comment by philips** [comment]
For some more background the OCI TOB has approved a new project for the OCI Image Format Spec which will be in a new repo and have a different set of maintainers. So, we need to rename this repo simply for clarity.

**Comment by xemul** [comment]
+1 for opencontainers/runtime-spec

**Comment by wking** [comment]
On Fri, Mar 25, 2016 at 10:40:04AM -0700, Chris Aniszczyk wrote:
> It's been suggested to rename this repo by the TOB to improve
> clarity…

While the TOB is deciding what to call the repo, they should probably
also figure out what to put here [1] and maybe talk about updating the
“the OCI Specification” language here [2] to account for multiple OCI
specifications.

[1]: https://github.com/opencontainers/specs/tree/v0.4.0#open-container-specifications
[2]: https://www.opencontainers.org/governance

**Comment by mrunalp** [comment]
opencontainers/runtime-spec works for me.

**Comment by vbatts** [comment]
opencontainers/runtime-spec works for me as well.

**Comment by tianon** [comment]
Sounds good to me also

**Comment by vishh** [comment]
+1

**Comment by hqhq** [comment]
opencontainers/runtime-spec works for me.

**Comment by iamanush** [comment]
+1 opencontainers/runtime-spec works

**Comment by philips** [comment]
@caniszczyk can you do this rename to runtime-spec? It seems OK to everyone and @crosbymichael verbally said OK on the call today.

**Comment by caniszczyk** [comment]
@philips it is done!

Thanks everyone!
