### ISSUE TITLE
Add Conformance Clause(s) to Spec

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/runtime-spec#367]
This was requested by the OCI TB Certification Program WG and I believe Stephen Walli (HPE) will be submitting a PR very soon.

**Comment by philips** [comment]
We will try and get this into v0.5.0 if it comes in today. Otherwise we will punt to v0.6.0.

**Comment by RobDolinMS** [comment]
I chatted with Stephen and expect a draft this afternoon.

**Comment by stephenrwalli** [comment]
I suggested additional language in a [pull request](https://github.com/stephenrwalli/runtime-spec/pull/1) on the runtime-spec file. Apologies if I'm out of order on workflow. Haven't directly contributed until now.

**Comment by wking** [comment]
On Wed, Apr 06, 2016 at 02:27:15PM -0700, Stephen Walli wrote:
> I suggested additional language in a [pull
> request](https://github.com/stephenrwalli/runtime-spec/pull/1) on
> the runtime-spec file.

The PR should probably target the opencontainers repo, not your
personal fork.

**Comment by RobDolinMS** [comment]
@stephenrwalli has opened PR #373 with proposed language.

**Comment by RobDolinMS** [comment]
With thanks to @mrunalp, this is addressed in PR #374

**Comment by mrunalp** [comment]
#374 is merged.
