### ISSUE TITLE
Id links in schema is broken

### ISSUE THREAD

**Issue by hqhq** [opencontainers/runtime-spec#387]
https://www.opencontainers.org/schema/
There is no such page. Haven't tried before, is that a regression or place holder?

ping @vbatts

**Comment by vbatts** [comment]
Either a) a placeholder; or b) more of a DNS based ID not required to
resolve. It would be nice, but not immediately necessary.

**Comment by hqhq** [comment]
OK, thanks for clarifying, I'll close the issue.
