### ISSUE TITLE
Why does rootfs path have to be relative? 

### ISSUE THREAD

**Issue by crosbymichael** [opencontainers/runtime-spec#389]
Ideally it is good to have the rootfs inside the bundle but I don't think it should be required.  When dealing with overlay drivers or things like btrfs/zfs it would be better to not required extra bind mounts just to put the rootfs inside the bundle.  Can we look at changing this requirement?

**Comment by wking** [comment]
On Tue, Apr 19, 2016 at 02:08:21PM -0700, Michael Crosby wrote:
> Ideally it is good to have the rootfs inside the bundle but I don't
> think it should be required.

I'm +1 on allowing absolute paths and punting policy decisions about
what a particular system will support to higher level tooling.

**Comment by wking** [comment]
Historical note: the current relative wording seems to date back to
77d44b10 (Update runtime.md, 2015-06-16, [1]), which is the
unmotivated dawn of time as far as this repository goes ;).

[1]: https://github.com/opencontainers/runtime-spec/commit/77d44b10d5df53ee63f0768cd0a29ef49bad56b6#diff-b84a8d65d8ed53f4794cd2db7e8ea731R234
