### ISSUE TITLE
Version not included on first page of runtime spec

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/runtime-spec#398]
When viewing a printed PDF or HTML version of the runtime spec, it is not clear what version (or date) you're looking at.  A possible fix would be to include the version (and date) in the title.  

For example:
* vX.Y.Z-dev during development
* vX.Y.Z (and date) when a release is created
* vX.Y+1.Z-dev after release

**Comment by vbatts** [comment]
Good point
