### ISSUE TITLE
Improve the CI output on failures

### ISSUE THREAD

**Issue by vbatts** [opencontainers/runtime-spec#421]
```bash
$ make .gitvalidation
/bin/sh: 1: test: 1.5: unexpected operator
/bin/sh: 1: test: 1.5: unexpected operator
/bin/sh: 1: test: 1.5: unexpected operator
git-validation -q -run DCO,short-subject,dangling-whitespace -v -range 78e6667ae2d67aad100b28ee9580b41b7a24e667..HEAD
1 issues to fix
make: *** [.gitvalidation] Error 1
The command "make .gitvalidation" exited with 2.
```
from https://travis-ci.org/opencontainers/runtime-spec/jobs/127598867#L185

**Comment by wking** [comment]
On Tue, May 03, 2016 at 11:53:59AM -0700, Vincent Batts wrote:
> git-validation -q -run DCO,short-subject,dangling-whitespace -v -range 78e6667ae2d67aad100b28ee9580b41b7a24e667..HEAD
> 1 issues to fix
> make: *** [.gitvalidation] Error 1

git-validation has been reasonably clear the last few times I've
looked at Travis logs where it complained.  Can we close this issue?
