### ISSUE TITLE
Problem building specification

### ISSUE THREAD

**Issue by nuest** [opencontainers/runtime-spec#454]
Hi! I'm really interested to get involved and t ostart I wanted to build the spec locally. I am still learning to use make, so I'm having some issues running it. Apologies for the newbie-level questions!

First, on my machine (Ubuntu 16.04 with GNU make 4.1) I have to explicitly set the SHELL variable, e.g. `make docs -e SHELL=bash` (with `sh` i get some unexpected operator errors).
Is that expected? Should I have this in my environment already? I assume this is to allow (power) users to configure their environment, but I just want to be sure.

Second, when I make the docs, I get an error message that docker does not find the image:

```
~/git/runtime-spec$ make docs -e SHELL=bash
mkdir -p output/ && \
/usr/bin/docker run \
-it \
--rm \
-v /home/daniel/git/runtime-spec/:/input/:ro \
-v /home/daniel/git/runtime-spec/output/:/output/ \
-u 1000 \
/usr/bin/pandoc -f markdown_github -t latex -o /output/docs.pdf /input/version.md /input/README.md /input/code-of-conduct.md /input/principles.md /input/style.md /input/ROADMAP.md /input/implementations.md /input/project.md /input/bundle.md /input/runtime.md /input/runtime-linux.md /input/config.md /input/config-linux.md /input/config-solaris.md /input/glossary.md
/usr/bin/docker: Error parsing reference: "/usr/bin/pandoc" is not a valid repository/tag.
See '/usr/bin/docker run --help'.
Makefile:29: recipe for target 'output/docs.pdf' failed
```

There actually is no image name in the created call, and never has been. _What am I missing here?_

Once I got this working I'd be happy to contribute some introductory documentation, if you agree that would be useful.

**Comment by vbatts** [comment]
The `SHELL=bash` is interesting. ubuntu must use `ash` as their `sh`.
As for the primary issue, that should be resolved now. Do a `git pull` and `make docs`.

**Comment by nuest** [comment]
Thanks! Everything works now.

**Comment by wking** [comment]
What operator errors were you seeing with your `sh`?  I don't think we need to do anything Bash-specific in the Makefile.

**Comment by nuest** [comment]
My apologies for the delay. I could reproduce the issue probably by going back to the specific commit. Just let me know if this would be helpful still. Thanks!
