### ISSUE TITLE
Suggestion: Add an Abstract section to spec

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/runtime-spec#506]
It would be useful to have a brief summary describing the OCI Runtime spec.  
This may just be a single paragraph of a few sentences.
This would be useful for people coming new to the spec or wanting to have a consistent brief description of the spec.

**Comment by wking** [comment]
On Thu, Jun 23, 2016 at 06:25:02AM -0700, Rob Dolin (MSFT) wrote:
> It would be useful to have a brief summary describing the OCI
> Runtime spec.

So a lead-in paragraph for [1] that sets the stage for the use-cases?

[1]: https://github.com/opencontainers/runtime-spec/tree/v1.0.0-rc1#use-cases

**Comment by RobDolinMS** [comment]
I've changed this to the 1.0.0 milestone as I think something like this is important for a complete spec.
