### ISSUE TITLE
Suggestion: clarify Masked and Readonly Paths

### ISSUE THREAD

**Issue by Mashimiao** [opencontainers/runtime-spec#509]
There is not clearly requirement for Masked or Readonly Paths.
I think we must definitely define they must be absolute path  or not in runtime spec.

**Comment by wking** [comment]
On Fri, Jun 24, 2016 at 02:31:48AM -0700, Ma Shimiao wrote:
> I think we must definitely define they must be absolute path or not
> in runtime spec.

This is related to a general need to specify the anchor for relative
paths [1].  If there is a config.md-wide entry like:

  Relative paths are interpreted relative to the directory holding
  config.json.

Then having relative paths here (or in other places) seems
sufficiently well-defined to me.

[1]: http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2016/opencontainers.2016-05-18-17.01.log.html#l-72
     and the next two lines.

**Comment by hqhq** [comment]
Fixed by: https://github.com/opencontainers/runtime-spec/pull/587
