### ISSUE TITLE
New Phone Number for Conference Line

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/runtime-spec#514]
There was a change in the phone number for the conference line, URL is the same.

Join the call: https://www.uberconference.com/opencontainers
Optional dial in number: 415-968-0849
No PIN needed

We need to update the README.

**Comment by wking** [comment]
On Thu, Jul 14, 2016 at 06:27:50PM -0700, Chris Aniszczyk wrote:
> Optional dial in number: 415-968-0849

Does that replace both of the current options (the 888 number and the
860 number)?

**Comment by caniszczyk** [comment]
@wking correct, it will replace the previous numbers.

The URL says the same though.

**Comment by wking** [comment]
On Thu, Jul 14, 2016 at 08:00:18PM -0700, Chris Aniszczyk wrote:
> @wking correct, it will replace the previous numbers.
> 
> The URL says the same though.

I've filed #515 to do this.
