### ISSUE TITLE
Consider using PullApprove's new DCO check feature

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/runtime-spec#516]
PullApprove now checks for the DCO Signed-off-by's tags:
https://github.com/pullapprove/support/issues/65#issuecomment-230831212

It could be interesting to enable this versus the current checks by @vbatts script

**Comment by cyphar** [comment]
*mumble* proprietary software *mumble*

**Comment by davegaeddert** [comment]
Hey guys, don't want to butt in here but I was talking with another PullApprove user (someone who is also interested in this DCO feature) and they're having the same discussion about not wanting to use a closed-source solution.

Do you have any other specific thoughts on this? I noticed on this repo that you're currently using Travis CI too -- is there specific justification for that?

**Comment by cyphar** [comment]
We use Jenkins for runC. We really should switch from PullApprove to https://lgtm.io/ (which is free software). And we can just continue using Jenkins for the DCO checking code. I really don't want to switch from a free software solution to a proprietary one -- that's working backwards.

**Comment by cyphar** [comment]
Not to mention that I cannot use any of the PullApprove dashboard stuff because they ask for insane OAuth permissions and I cannot verify that they don't do anything dodgy with them (it includes the ability to modify private repositories **of organisations I'm a member of).

**Comment by davegaeddert** [comment]
Hmm. I'm getting an SSL warning on https://lgtm.io. Looks like it's now https://lgtm.com? Is that open source or just free in terms of cost? I hear you on not wanting to work backwards, just want to make sure I understand what the hang-ups are.

The OAuth permissions are definitely an issue. We're working to make a stepped flow where it asks for public repo permissions by default, private if you want to give it.

**Comment by wking** [comment]
On Thu, Jul 21, 2016 at 08:43:19AM -0700, Dave Gaeddert wrote:
> Is that open source or just free in terms of cost?

More background on this in opencontainers/runC#916.

**Comment by davegaeddert** [comment]
Thanks @wking. I wondered if it was https://github.com/lgtmco/lgtm, which I think is different yet from lgtm.io/lgtm.com. Appreciate the background. And I will say that the odds that PullApprove will be open-sources are, at this point, pretty low. We need to make money to keep working on it, and haven't yet come up with a good way to do both ;)

**Comment by cyphar** [comment]
@davegaeddert It is free software in the FSF definition of the word, I don't use the term "free software" to refer to gratis software (nor do I use the term "open source" for other, more subtle reasons).

**Comment by davegaeddert** [comment]
@cyphar fair enough. Also, just in case you are curious, due to this conversation and a couple of others recently we prioritized the OAuth permissions issue yesterday. Now when you log in it will only ask for public repo access to start, then you can add private repo access later if you wish.

**Comment by crosbymichael** [comment]
I'm fine with using this for the DCO checks as well.

**Comment by duglin** [comment]
I've used it and it works well.
