### ISSUE TITLE
The reference to "schema/schema.json" is bad

### ISSUE THREAD

**Issue by hapnermw** [opencontainers/runtime-spec#517]

**Comment by wking** [comment]
This is probably talking about [1], which should have been updated in
#481 or the #498 fixup.  Are you working on a PR, or shall I submit
one?

[1]: https://github.com/opencontainers/runtime-spec/blame/bbaf29e6173a1ef017d75db11e4d698ac4de0f1e/config.md#L4

**Comment by vbatts** [comment]
hmm. @hapnermw do you have any more specifics?
