### ISSUE TITLE
Add version number to release files generated

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/runtime-spec#535]
Repro:
1. https://github.com/opencontainers/runtime-spec/releases
2. Click on the HTML or PDF versions of the runtime spec
3. Check your downloads folder

RESULT:
* File name is oci-runtime-spec

EXPECT:
* File names is oci-runtime-spec-v1.0.0-rc1

**Comment by RobDolinMS** [comment]
Tagging @vbatts.  It looks like this is already working in the image-spec repo so hopefully this might be a quick fix.

**Comment by hqhq** [comment]
I don't think image-spec did this in source code level, so maybe it's just a release issue, or do you think we should contain version number in files created by `make docs`?

**Comment by RobDolinMS** [comment]
@hqhq I'm not sure if this is done in automated code for the release or if this is done manually as part of the release process, but for people who consume the HTML or PDF formats of spec, it is useful to have the version indicated in the filename.

**Comment by RobDolinMS** [comment]
(I'm not able to set Milestone, but I recommend this be set to Milestone=1.0.0 or Milestone=1.0.0-rc2)

**Comment by vbatts** [comment]
@RobDolinMS ideally it'll include the version in the doc as well as the file name. I think i just forgot a release step there on the 1.0.0-rc1 docs

**Comment by vbatts** [comment]
I fixed the filenames for the most recent release.

**Comment by RobDolinMS** [comment]
Thanks @vbatts.  Looks like this is now fixed for the latest release at: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc1
