### ISSUE TITLE
Inconsistent size values in example

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/runtime-spec#580]
There are two instances of uidMappings in the spec and they have wildly different values for "size" (10 and 3200)

Is this intentional or possibly an error?

(Same applies for gidMappings)

**Comment by wking** [comment]
On Mon, Sep 19, 2016 at 03:34:04PM -0700, Rob Dolin (MSFT) wrote:
> There are two instances of uidMappings in the spec and they have
> wildly different values for "size" (10 and 3200)
> 
> Is this intentional or possibly an error?

Both are potentially valid.  The @mrunalp suggested 32k [1] (although
I haven't been able to turn up a reason).  I don't remember anyone
advocating for 10, so I'm fine going with 32000 in all of our mapping
examples.

[1]: https://github.com/opencontainers/runtime-spec/pull/370#r58783031

**Comment by RobDolinMS** [comment]
Proposed #613 to resolve this.

**Comment by cyphar** [comment]
#613 has been merged (so this should be closed).
