### ISSUE TITLE
Planning for 1.0-RC3 release?

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/runtime-spec#594]
It's been over a month since the last release, what's the plan for 1.0-RC3?

**Comment by caniszczyk** [comment]
cc: @opencontainers/runtime-spec-maintainers

**Comment by cyphar** [comment]
The big blocker is currently #513. And that's blocked on opencontainers/runc#1018, among other things.

**Comment by caniszczyk** [comment]
Thanks @cyphar, just was curious why I didn't see a 1.0-RC3 milestone here:
https://github.com/opencontainers/runtime-spec/milestones

**Comment by vbatts** [comment]
https://github.com/opencontainers/runtime-spec/milestone/12 there. But how to cross-link to the runc issue?

**Comment by wking** [comment]
On Mon, Oct 24, 2016 at 08:31:07AM -0700, Vincent Batts wrote:
> https://github.com/opencontainers/runtime-spec/milestone/12 there. But how to cross-link to the runc issue?

Move #513 into the -rc3 milestone and rely on maintainers to remember that it's tied up with opencontainers/runc#1018?

**Comment by caniszczyk** [comment]
This is being voted upon now and looks like it will pass.

https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/vm9laWGriwE
