### ISSUE TITLE
Mounting cgroups in a container

### ISSUE THREAD

**Issue by mrunalp** [opencontainers/runtime-spec#66]
This issue has been created to continue the discussion in #65

**Comment by mrunalp** [comment]
The main feature that we are asking for is introspection so that the container process can see its own cgroups. The could be mounted RO, so the container can't modify its own cgroups. The main contention here is where should these be mounted and if we can come up with a standard location then there could be some tooling that could benefit from it.

@philips @crosbymichael

**Comment by philips** [comment]
Are there applications today that expect to have a sub-tree cgroup mount? If not I would suggest that we make the container cgroup path easily discoverable via an environment variable.

The basic process would be to mount the entire heirarchy as RO and then via an environment variable like, `CGROUP_SUBTREE=/foo`, the user can find their container location by appending `/sys/fs/cgroup` to that subtree path.

If in the future we are able to fix-up the Kernel we could then make `CGROUP_SUBTREE=/` and always mount a subtree to `/sys/fs/cgroup` and no code changes would be required.

Thoughts?

**Comment by alban** [comment]
I think the canonical way to know the container cgroup path should be to parse `/proc/1/cgroup` (pid 1 refers to the pid leader in the container). For example,
```
cat /proc/1/cgroup | grep ^1: | sed 's/^[^:]*:[^:]*://'
```
On the host, this returns `/`. In containers, this would return a longer path such as `/system.slice/docker-ca590ce841b7a8f66b41a85fc170540ce9d219dbd03b1086528945117d276612.scope`.

Applications should expect to find `/sys/fs/cgroup/$CONTROLLER/$CGROUP_SUBTREE` where `$CONTROLLER` is for example `systemd`.

If in the future the kernel implements cgroup namespacing, then `/proc/1/cgroup` would show the path `/` in the container.

**Comment by mrunalp** [comment]
The downside of mounting the entire cgroups hierarchy is that the container can read the limits of all the other containers. 

I agree that it will be great if we see / when the kernel namespacing is implemented. However, what we are proposing is an approximation of that as the container can only see its own cgroups and not of other containers/processes on the host.

**Comment by philips** [comment]
I understand the downside and fully sympathize with the "annoyingness" of being able to read the limits of other cgroups. But, I would rather wait for the Kernel to correctly virtualize/namespace this and then enable the Kernel namespacing instead of working around the lack of namespaces and making things internally inconsistent.

**Comment by iaguis** [comment]
> I understand the downside and fully sympathize with the "annoyingness" of being able to read the limits of other cgroups. But, I would rather wait for the Kernel to correctly virtualize/namespace this and then enable the Kernel namespacing instead of working around the lack of namespaces and making things internally inconsistent.

:+1:

**Comment by mrunalp** [comment]
@philips I agree.

**Comment by vishh** [comment]
Mounting cgroups would impact checkpoint - restore functionality. FYI.

**Comment by LK4D4** [comment]
@vishh Yeah, we mounting subtree in runc. And I believe @avagin handled that stuff.

**Comment by philips** [comment]
So, I am going to put up a PR that will spec out mounting the system cgroup as a read-only bind-mount and the 'sub-cgroup' of the container optionally as a read-write bind-mount.

This should be backwards compatible once the cgroup namespace is merged and requires no "magic". @vmarmol Can you ping Aditya about: https://lkml.org/lkml/2014/10/19/4

**Comment by vmarmol** [comment]
I pinged Aditya and he mentioned he has mostly not had time to continue the patch set and he wasn't getting any pressure to get it in. The only negative feedback he received on the patch set was that it only worked on unified hierarchy. He says he can make it work with the split hierarchy, but that it'd be more work overall.

**Comment by LK4D4** [comment]
Here we have sorta implementation detail. For example in `runc` you can specify `Type` for `Mount` as `cgroup` and then cgroups will be mounted inside container. So, theoretically mounts isn't very well standardized :)

**Comment by philips** [comment]
@vmarmol If we can push for just unified that would work for me.

**Comment by vmarmol** [comment]
That was a primary complaint from reviewers, maybe the can be convinced
otherwise

**Comment by mrunalp** [comment]
cgroups namespaces patch has been revived http://lists.linuxfoundation.org/pipermail/containers/2015-November/036378.html :)

**Comment by vishh** [comment]
I chatted briefly with Aditya about this patch. This should get merged
(hopefully) soon :)

**Comment by vbatts** [comment]
SUPER!

**Comment by philips** [comment]
OK, the patch is super exciting. Thanks for the update @mrunalp and @vishh.

This makes it easy to argue for mounting cgroup hierarchy read-only with the sub-cgroup as read-write (https://github.com/opencontainers/specs/issues/66#issuecomment-121729849). So, lets push forward on that.

**Comment by ashahab-altiscale** [comment]
Hmm, why is this part of the spec? Isn't this just a mount config as @LK4D4 says?

**Comment by hqhq** [comment]
cgroup namespace support was added by: https://github.com/opencontainers/runtime-spec/pull/397

I think we can close this.
