### ISSUE TITLE
Remove unused branches from this repo

### ISSUE THREAD

**Issue by justincormack** [opencontainers/runtime-spec#667]
There are 4 unused branches on this repo that seem to be left over from old PRs, can they be deleted?

**Comment by caniszczyk** [comment]
@justincormack I removed a couple that were clearly not relevant.

The rest have open PRs associated with them so I won't remove them until they are closed.

**Comment by wking** [comment]
On Mon, Jan 23, 2017 at 07:16:56AM -0800, Chris Aniszczyk wrote:
> @justincormack I removed a couple that were clearly not relevant.
>
> The rest have open PRs associated with them so I won't remove them
> until they are closed.

The protobuf branch [1] is not assiciated with a PR (it's currently
pointing at dca1dfd, which is the master commit that merged #181).
After removing that, the only non-master branch will be #661's
RobDolinMS-459-replace.

[1]: https://github.com/opencontainers/runtime-spec/tree/protobuf

**Comment by crosbymichael** [comment]
Removed them all.  People should be developing on their forks and not using this upstream repo at all.  Nothing was pending anyways on those branches.

**Comment by crosbymichael** [comment]
If you are a maintainer on this repo or have write access for some odd reason, do not push branches here, you have a fork for a reason.
