### ISSUE TITLE
config-linux: Many config properties without RFC 2119 language

### ISSUE THREAD

**Issue by wking** [opencontainers/runtime-spec#746]
I've filed #745 to add RFC 2119 language to `disableOOMKiller`, but there are many other settings in `config-linux.md` without RFC 2119 wording to connect them with [compliance testing][1] (e.g. [`oomScoreAdj`][2], [`memory`][3], …).  Without RFC 2119 language, it is not very clear what config-author and runtime responsibilities are intended to be.  And it is clear that, whatever the intentions were:

* A config would be technically valid with ridiculous values in the setting (e.g. `"oomScoreAdj" = 999999999999999999999999999999999999999999999999999999999999999999`).
* A runtime would be technically valid if it silently ignored the setting.

I think we should address this before cutting 1.0.  #745 is a (small) step in that direction, but I wanted to open this issue to get feedback on the issue in general (without getting bogged down on a specific setting).

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/spec.md#notational-conventions
[2]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/config-linux.md#set-oom_score_adj
[3]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/config-linux.md#memory

**Comment by wking** [comment]
#728 is another PR that is partially addressing this.

**Comment by wking** [comment]
In the meeting today, folks were asking for a way to close this issue, so here's a checklist of all the properties in config-linux for whether or not they have sufficient runtime-facing RFC 2119 language for compliance testing (as of 138ad89):

* [ ] `namespaces` (#767)
* [ ] `uidMappings`
* [ ] `gidMappings`
* [x] `devices`
    * [ ] `type`
    * [ ] `path`
    * [ ] `major`
    * [ ] `minor`
    * [ ] `fileMode`
    * [ ] `uid`
    * [ ] `gid`
* [x] default devices
    * [x] `/dev/null`
    * [x] `/dev/zero`
    * [x] `/dev/random`
    * [x] `/dev/urandom`
    * [x] `/dev/tty`
    * [ ] `/dev/console`
    * [ ] `/dev/ptmx`
* [x] `cgroupsPath`
* [ ] `resources`
    * [ ] `devices`
        * [ ] `allow`
        * [ ] `type`
        * [ ] `major`
        * [ ] `minor`
        * [ ] `access`
    * [ ] `disableOOMKiller`
    * [ ] `oomScoreAdj`
    * [ ] `memory`
        * [ ] `limit`
        * [ ] `reservation`
        * [ ] `swap`
        * [ ] `kernel`
        * [ ] `kernelTCP`
        * [ ] `swappiness`
    * [ ] `cpu`
        * [ ] `shares`
        * [ ] `quota`
        * [ ] `period`
        * [ ] `realtimeRuntime`
        * [ ] `realitimePeriod`
        * [ ] `cpus`
        * [ ] `mems`
    * [ ] `blockIO`
        * [ ] `blkioWeight`
        * [ ] `blkioLeafWeight`
        * [ ] `blkioWeightDevice`
        * [ ] `blkioThrottleReadBpsDevice`
        * [ ] `blkioThrottleWriteBpsDevice`
        * [ ] `blkioThrottleReadIOPSDevice`
        * [ ] `blkioThrottleWriteIOPSDevice`
    * [ ] `hugepageLimits`
        * [ ] `pageSize`
        * [ ] `limit`
    * [ ] `network`
        * [ ] `classID`
        * [ ] `priorities`
    * [ ] `pids`
        * [ ] `limit`
* [ ] `intelRdt`
    * [ ] `l3CacheSchema`
* [ ] `sysctl`
* [ ] `seccomp`
    * [ ] `defaultAction`
    * [ ] `architectures`
    * [ ] `syscalls`
        * [ ] `names`
        * [ ] `action`
        * [ ] `args`
* [ ] `rootfsPropagation`
* [ ] `maskedPaths`
* [ ] `readonlyPaths`
* [ ] `mountLabel`

Ideally we'd close each of these with a compliance test in runtime-tools, but I'm currently checking them off when I feel like there is sufficient spec clarity, regardless of the existence of compliance tests.  If folks feel like I should be checking something off that is unchecked, landing runtime-tools compliance tests (or pointing out the existing runtime-tools tests which I've overlooked) would be a convincing way to argue for checking the property off.  In some cases (e.g. `oomScoreAdj`), I have left the entry unchecked because [the current test][1] assumes `/proc/1/oom_score_adj` which is not backed by spec language (and which is only correct when the config calls for a new PID namespace).

I'll come back and update this comment as work continues.

[1]: https://github.com/opencontainers/runtime-tools/blob/8addcc695096a0fc61010af8766952546bba7cd0/cmd/runtimetest/main.go#L449

**Comment by crosbymichael** [comment]
We don't want to go down this route.  The actually changes that were submitted are coupling the spec to very, very implementation specific functionality of kernels, versions, and posix specs.
