### ISSUE TITLE
config-linux: Move 'oomScoreAdj' outside of 'resources'?

### ISSUE THREAD

**Issue by wking** [opencontainers/runtime-spec#782]
The only discussion related to this is in #236 and #292, where the relationship between `oomScoreAdj` and `disableOOMKiller` is raised.  But since #137 `resources` has been tied to cgroups, and `oomScoreAdj` is not about cgroups.  We [currently have][1]:

> You can configure a container's cgroups via the `resources` field of the Linux configuration.

I suggest we move the property from `linux.resources.oomScoreAdj` to `linux.oomScoreAdj` so config authors and runtimes don't have to worry about what `cgroupsPath` means if the only entry in `resources` is `oomScoreAdj`.

[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config-linux.md#L185

**Comment by crosbymichael** [comment]
If anything it should probably go on the process
