### ISSUE TITLE
Camel casing needs fixing in config.go and matching schema

### ISSUE THREAD

**Issue by jhowardmsft** [opencontainers/runtime-spec#857]
As per this comment: https://github.com/opencontainers/runtime-spec/pull/828#discussion_r118375184

**Comment by wking** [comment]
If we're going to adjust any of this casing, I'd *really* like to have
that happen before the next tag.  #842 (the proposed rc6, currently at
4e3635b) has:

  $ git checkout origin/pr/842
  $ git grep '`' -- config-windows.md
  …
  config-windows.md:* **`sandboxSize`** *(uint64, OPTIONAL)* - specifies the minimum size of the system drive in bytes.
  …
  config-windows.md:* **`egressBandwidth`** *(uint64, OPTIONAL)* - specified the maximum egress bandwidth in bytes per second for the container.
  …
  config-windows.md:The `credentialspec` is a JSON object whose properties are implementation-defined.
  …

And master has:

  $ git checkout origin/master
  $ git describe
  v1.0.0-rc5-194-g9151c77
  $ git grep '`' -- config-windows.md
  …
  config-windows.md:* **`sandboxSize`** *(uint64, OPTIONAL)* - specifies the minimum size of the system drive in bytes.
  …
  config-windows.md:* **`endpointList`** *(array of strings, OPTIONAL)* - list of HNS (Host Network Service) endpoints that the container should connect to.
  config-windows.md:* **`allowUnqualifiedDNSQuery`** *(bool, OPTIONAL)* - specifies if unqualified DNS name resolution is allowed.
  config-windows.md:* **`DNSSearchList`** *(array of strings, OPTIONAL)* - comma seperated list of DNS suffixes to use for name resolution.
  config-windows.md:* **`networkSharedContainerName`** *(string, OPTIONAL)* - name (ID) of the container that we will share with the network stack.
  …
  config-windows.md:The `credentialspec` is a JSON object whose properties are implementation-defined.
  …
  config-windows.md:* **`utilityvmpath`** *(string, OPTIONAL)* - specifies the path to the image used for the utility VM. This would be specified if using a base image which does not contain a utility VM image. If not supplied, the runtime will search the container filesystem layers from the bottom-most layer upwards, until it locates "UtilityVM", and default to that path.
  config-windows.md:* **`sandboxpath`** *(string, REQUIRED)* - specifies the root of the path to the sandbox to be used for the container.
  …

which both have camelCase (sandboxSize, etc.) and lowercase
(credentialspec) properties.  Casing is a really silly thing to break
backwards compat on.  We already have backwards-incompatible changes
post the currently proposed rc6 (e.g. #801), but I'd rather not break
compat again after we cut rc7 (or 1.0, or whatever comes after rc6).

**Comment by jhowardmsft** [comment]
Agreed. As soon as that other PR is merged, I'll get on it.

**Comment by wking** [comment]
On Thu, May 25, 2017 at 10:48:13AM -0700, John Howard wrote:
> Agreed. As soon as that other PR is merged, I'll get on it.

Maintainers may also want to milestone this issue 1.0 freeze [1] so it
doesn't slide to post-1.0.

[1]: https://github.com/opencontainers/runtime-spec/milestone/15
