### ISSUE TITLE
Fix docs.oracle.com links

### ISSUE THREAD

**Issue by epilatow** [opencontainers/runtime-spec#864]
the zoneadmd.1m and priv-str-to-set.3c docs.oracle.com links in config-solaris.md are broken.  the zonecfg.1m link (in config.md and config-solaris.md) also points to the solaris 11.2 man page.  all the links should be updated to point to the latest solaris 11.3 man pages.

**Comment by wking** [comment]
Do we want a PR fixing these links to be part of 1.0?  I'm happy to work one up, and it seems like it would be easy enough to review.

**Comment by wking** [comment]
Actually, it looks like this was fixed by #865.  We can probably close this issue.
