### ISSUE TITLE
when should prestart hooks be called

### ISSUE THREAD

**Issue by hqhq** [opencontainers/runtime-spec#909]
I just realized that we define [prestart hooks MUST be called after the start operation is called](https://github.com/opencontainers/runtime-spec/blob/v1.0.0/config.md#prestart), it's been there since we restore hook language removed by create/start split in #532 , but we actually call prestart hooks in create operation which before start operation in runc, and this should be the right approach in practice, should we amend language in runtime-spec or should we reconsider implementation in runc?

**Comment by wking** [comment]
On Thu, Aug 17, 2017 at 05:29:46AM -0700, Qiang Huang wrote:
> … but we actually call prestart hooks in create operation which
> before start operation in runc…

As I mentioned in f636808bf's commit message from #532, I think a hook
that executes at the end of the ‘create’ operation should be called
‘postcreate’.

**Comment by hqhq** [comment]
Logically I think the definition is reasonable in runtime-spec, I think we can discuss this in runc first. Opened https://github.com/opencontainers/runc/issues/1574 .
