### ISSUE TITLE
should duplicated mount elemnts allowed?

### ISSUE THREAD

**Issue by Mashimiao** [opencontainers/runtime-spec#912]
Hi, everyone
In config.md, we just require that mounts should be mounted in order and nested mounts are not allowed in windows.
I know nested mounts and over mounts are allowed.
But does duplicated mounts(both of the mount elements are totally same) really make sense?
Should we strictly limit such situation?

**Comment by crosbymichael** [comment]
I would error on the side of yes, allow it.

There is probably some usecase out there that needs this and to compare every element, we would have to lookup every field in the mount struct, compare all options, etc...

overmounts can be used to mask out some system level paths so idk, it may not be worth adding this restriction and then having to remove it later if someone actually requires it from some odd reason.

**Comment by tianon** [comment]
Agree with Michael; it's odd, but totally allowed by the kernel and I don't
see a great reason to make implementors lives harder by forcing it
otherwise.

**Comment by cyphar** [comment]
I also imagine there are cases where it's useful. For example, I believe that LXC's `cgroupfs` does some interesting tricks where they mount themselves over an existing cgroupfs mount, and by opening a `dirfd` of the mount before mounting over it they can access the underlying filesystem. While that usage wouldn't clash here, I can imagine a nested scenario where that might happen.

**Comment by Mashimiao** [comment]
OK, got it. Thanks for your reply.
