### ISSUE TITLE
Is there a uniqueness requirement for `cgroupsPath`?

### ISSUE THREAD

**Issue by ijc** [opencontainers/runtime-spec#944]
What are the expected semantics of having multiple containers with the same value for `cgroupsPath`?

In https://github.com/linuxkit/kubernetes/issues/23 the behaviour I'm seeing is that when the first container to share a given `cgroupsPath` exits containerd calls `runc delete --all` on it which nukes the processes of all of the containers with that `cgroupsPath`.

The runtime spec doesn't say explicitly but the fact that the examples are things like `/myRuntime/myContainer` seems to imply that it should be unique for each container. Is that right? (If so then the observed behaviour seems entirely reasonable).

**Comment by cyphar** [comment]
No there is **no** uniqueness requirement for `cgroupsPath`. Aside from the spec not specifying a uniqueness requirement, [the current text](https://github.com/opencontainers/runtime-spec/blob/v1.0.1/config-linux.md#cgroups-path) is quite clear that attaching to existing cgroups is very much supported (emphasis added).

>  **`cgroupsPath`** (string, OPTIONAL) path to the cgroups.
> It can be used to either control the cgroups hierarchy for containers or to **run a new process in an existing container**.
> 
> The value of `cgroupsPath` MUST be either an absolute path or a relative path.
> * In the case of an absolute path (starting with `/`), the runtime MUST take the path to be relative to the cgroups mount point.
> * In the case of a relative path (not starting with `/`), the runtime MAY interpret the path relative to a runtime-determined location in the cgroups hierarchy.
> 
> If the value is specified, the runtime MUST **consistently attach to the same place in the cgroups hierarchy given the same value of `cgroupsPath`**.
> If the value is not specified, the runtime MAY define the default cgroups path.
> Runtimes MAY consider certain `cgroupsPath` values to be invalid, and MUST generate an error if this is the case.
> 
> Implementations of the Spec can choose to name cgroups in any manner.
> The Spec does not include naming schema for cgroups.
> The Spec does not support per-controller paths for the reasons discussed in the [cgroupv2 > documentation][cgroup-v2].
> The cgroups will be created **if they don't exist**.
> 
> You can configure a container's cgroups via the `resources` field of the Linux configuration.
> Do not specify `resources` unless limits have to be updated.
> For example, **to run a new process in an existing container** without updating limits, `resources` need not be specified.
>
> Runtimes MAY attach the container process to additional cgroup controllers beyond those necessary to fulfill the `resources` settings.

**Comment by wking** [comment]
On Mon, Dec 18, 2017 at 02:50:18PM +0000, Ian Campbell wrote:
> In https://github.com/linuxkit/kubernetes/issues/23 the behaviour
> I'm seeing is that when the first container to share a given
> `cgroupsPath` exits containerd calls `runc delete --all` on it which
> nukes the processes of all of the containers with that
> `cgroupsPath`.

Reading over that issue, the bit that strikes me is [1]:

  runc kill --all ends up calling into a function signalAllProcess
  which has a comment…

I think that's the problem.  If one container creates a new PID
namespace for its container process, and later that container process
is killed, all processes inside that PID namespace will die.  But if
you have two containers which have separate PID namespaces and a
shared cgroupsPath, then killing one container should not affect the
other.  So I think whoever is calling ‘runc kill --all’ should be more
conservative and drop the ‘--all’.

[1]: https://github.com/linuxkit/kubernetes/issues/23#issuecomment-352013142

**Comment by ijc** [comment]
@cyphar thanks for the clarification.

> the current text is quite clear that attaching to existing cgroups is very much supported (emphasis added).

My first reading of the text which you highlighted ("run a new process in an existing container." and such) was that it applied to `runc exec` rather than `runc create/start/run`, I think that is the source of the ambiguity.

Apart from that your answer makes it very clear that something odd is going on, I'll figure out whether to raise a `runc` or a `containerd` issue and do so.

**Comment by cyphar** [comment]
@ijc `exec` is [not supported in the specification](https://github.com/opencontainers/runtime-spec/blob/v1.0.1/runtime.md#warnings) as a first-class citizen because it can be implemented using `create` and `start` (and because there are many, many, many points of disagreement between runtimes on how `exec` should work -- so it was punted on). Thus `config.json` in the spec refers to `create/start`.

I'm guessing it's a containerd issue, because in runc we don't delete cgroups indiscriminately.

**Comment by ijc** [comment]
I didn't know that, thanks, closing.

I think I'll report against containerd, I agree it is the most likely culprit at this point.
