### ISSUE TITLE
Seccomp Errno, return code

### ISSUE THREAD

**Issue by sargun** [opencontainers/runtime-spec#960]
Currently, there is no way to specify the errno code when in LinuxSeccomp policies. It would be nice to be able to specify it.

**Comment by flx42** [comment]
Ping, I would also like this to be added in the spec.

Looks like [the spec](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#seccomp) doesn't even mention which value of errno should be used. `runc` uses `EPERM` so maybe this should be called out as a first step.

**Comment by wking** [comment]
Previous discussion [here][1].  I'm still in favor of either making this configurable or adding a requirement for runtimes to use `EPERM`.

[1]: https://groups.google.com/a/opencontainers.org/forum/m/#!topic/dev/rKrj2LcUyA8

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/opencontainers/runtime-spec/pull/1041?

**Comment by cyphar** [comment]
Yeah this was fixed by #1041.
