### ISSUE TITLE
config-linux: improving description about rootfs mount propagation

### ISSUE THREAD

**Issue by dongsupark** [opencontainers/runtime-spec#973]
Recently I had a look into the [rootfs mount propagation section](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#rootfs-mount-propagation) in the spec, with @alban and @iaguis. I think there's a room for improvement in the section.

First of all, the description `Its value is either slave, private, shared or unbindable` is not exactly correct, because it can be also `slave and shared`. Is it ok to add a new mode for slave+shared in the spec?

I think the section needs some additional explanation with general idea about mount propagation, at least in one paragraph. Currently it simply points to the [shared subtrees document](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) in the Linux kernel, which is not exactly readable for all readers. Is it ok to add some explanation in the section of runtime-spec?

I'm aware that there have been issues regarding the topics, for example https://github.com/opencontainers/runtime-spec/issues/923. Though I'm not sure what the general consensus is.

**Comment by alban** [comment]
Also, the value 'shared' by itself is not clear. It could mean
1. 'shared' with the mount in the host namespace, or 
2.  'shared' (i.e. /proc/$pid/mountinfo would show 'shared:xx') but alone in its mount peer group.

IMO the second is useful for example when doing nested containers. I don't see the point of the first.

**Comment by cyphar** [comment]
> is not exactly correct, because it can be also slave and shared.

I'm not sure what you mean by this -- according to `mount(2)` you can only have one propagation type for any given mount:

> If  mountflags  includes  one  of MS_SHARED, MS_PRIVATE, MS_SLAVE, or MS_UNBINDABLE (all available since Linux 2.6.15), then the propagation type of an existing mount is changed. **If more than one of these flags is specified, an error results.** [emphasis mine]

There's also the point that `slave` and `shared` have precisely opposite effects when it comes to propagation of mounts and unmounts underneath the mount (in `slave` they do not propagate, in `shared` they do) and the behaviour with the master peer group is the same. So I'm a little confused what `shared`+`slave` would actually do.

**Comment by cyphar** [comment]
Ah sorry, I wasn't aware of that. In that case, yeah we probably should have a `mountPropagation` option to specify `shared+slave`.
